apiVersion: v1
kind: Namespace
metadata:
  name: gis-platform
  labels:
    name: gis-platform
    istio-injection: enabled
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgis-cluster
  namespace: gis-platform
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  
  postgresql:
    parameters:
      shared_preload_libraries:
        - "pg_stat_statements"
        - "postgis-3"
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "1GB"
      maintenance_work_mem: "64MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "8MB"
      huge_pages: "try"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
  
  bootstrap:
    initdb:
      database: gis_platform
      owner: gis_admin
      secret:
        name: postgis-credentials
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS postgis;
        - CREATE EXTENSION IF NOT EXISTS postgis_topology;
        - CREATE EXTENSION IF NOT EXISTS postgis_raster;
        - CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
        - CREATE EXTENSION IF NOT EXISTS btree_gist;
        - ALTER DATABASE gis_platform SET search_path TO public,postgis,topology;
  
  monitoring:
    enabled: true
    customQueriesConfigMap:
      name: postgis-monitoring-queries
      key: queries.yaml
