#!/bin/bash

# Spatial Performance Audit Runner
# Generated by database-spatial-agent

echo "🔍 Starting GIS Platform Spatial Performance Audit..."
echo "================================================="

# Check if required dependencies are available
command -v ts-node >/dev/null 2>&1 || { 
    echo "❌ ts-node is required but not installed. Install with: npm install -g ts-node"
    exit 1
}

# Create reports directory if it doesn't exist
mkdir -p reports

# Set environment variables if not set
if [ -z "$DATABASE_URL" ]; then
    echo "⚠️ DATABASE_URL not set, using default from .env"
    if [ -f .env ]; then
        export $(cat .env | grep -v '^#' | xargs)
    fi
fi

echo "📊 Running spatial performance audit..."
echo ""

# Run the audit script
ts-node src/scripts/spatial-performance-audit.ts

# Check if audit completed successfully
if [ $? -eq 0 ]; then
    echo ""
    echo "✅ Spatial performance audit completed successfully!"
    echo ""
    echo "📋 Report saved in reports/ directory"
    echo ""
    echo "🔧 Quick Actions:"
    echo "  • Review critical issues first"
    echo "  • Run suggested migrations: pnpm run db:migrate"
    echo "  • Optimize tables: VACUUM ANALYZE on large tables"
    echo "  • Monitor query performance with EXPLAIN ANALYZE"
    echo ""
    echo "📈 Suggested Next Steps:"
    echo "  1. Address any critical performance issues"
    echo "  2. Implement recommended indexes"
    echo "  3. Schedule regular VACUUM and ANALYZE"
    echo "  4. Monitor spatial query patterns"
    echo "  5. Consider geometry simplification for web tiles"
else
    echo ""
    echo "❌ Spatial performance audit failed!"
    echo "Check the error messages above and ensure:"
    echo "  • Database is accessible"
    echo "  • PostGIS extension is installed"
    echo "  • Required permissions are available"
    exit 1
fi