apiVersion: orchestration/v1
kind: OrchestrationConfiguration
metadata:
  name: gis-platform-orchestration
  version: 1.0.0
  environment: production
spec:
  autonomy:
    level: SUPERVISED
    decisionThresholds:
      confidence: 75
      complexity: 60
      risk: 30
    humanInterventionRules:
      alwaysRequireFor:
        - DATABASE_MIGRATION
        - PRODUCTION_DEPLOYMENT
        - SECURITY_INCIDENT
      complexityThreshold: 80
      riskThreshold: 50

  performanceThresholds:
    taskCompletionTime:
      excellent: 30000    # 30 seconds
      good: 60000         # 1 minute
      acceptable: 300000  # 5 minutes
    successRate:
      excellent: 0.95     # 95%
      good: 0.90          # 90%
      acceptable: 0.80    # 80%
    resourceUsage:
      cpu: 80             # 80%
      memory: 85          # 85%
      network: 70         # 70%

  globalSettings:
    maxConcurrentTasks: 50
    defaultTimeout: 300000      # 5 minutes
    retryAttempts: 3
    escalationTimeout: 600000   # 10 minutes

  agents:
    - id: frontend-ui-agent
      name: Frontend UI Development Agent
      type: frontend
      autonomyLevel: SUPERVISED
      capabilities:
        - TYPESCRIPT_GENERATION
        - REACT_COMPONENTS
        - API_DESIGN
        - TEST_GENERATION
      specializations:
        - React Native Web development
        - MapLibre GL JS integration
        - Mobile-responsive design
        - Performance optimization
      constraints:
        - Must use TypeScript strict mode
        - Must implement accessibility standards
        - Must follow component patterns
      performance:
        tasksCompleted: 0
        successRate: 0.95
        averageTime: 45000
        lastActive: "2025-01-01T00:00:00Z"

    - id: backend-api-agent
      name: Backend API Development Agent
      type: backend
      autonomyLevel: SUPERVISED
      capabilities:
        - API_DESIGN
        - TYPESCRIPT_GENERATION
        - PERFORMANCE_TUNING
        - TEST_GENERATION
      specializations:
        - Node.js Express development
        - RESTful API design
        - Authentication systems
        - Data validation
      constraints:
        - Must validate all inputs
        - Must implement rate limiting
        - Must use parameterized queries
      performance:
        tasksCompleted: 0
        successRate: 0.92
        averageTime: 60000
        lastActive: "2025-01-01T00:00:00Z"

    - id: postgis-optimization-agent
      name: PostGIS Database Optimization Agent
      type: database
      autonomyLevel: MANAGED
      capabilities:
        - SPATIAL_QUERY_OPTIMIZATION
        - INDEX_MANAGEMENT
        - PERFORMANCE_TUNING
        - GEOMETRY_PROCESSING
      specializations:
        - PostGIS spatial operations
        - GIST index optimization
        - Query plan analysis
        - Vacuum operations
      constraints:
        - Must create concurrent indexes
        - Must validate geometries
        - Must maintain SRID consistency
      performance:
        tasksCompleted: 0
        successRate: 0.88
        averageTime: 120000
        lastActive: "2025-01-01T00:00:00Z"

    - id: infrastructure-automation-agent
      name: Infrastructure Automation Agent
      type: infrastructure
      autonomyLevel: MANAGED
      capabilities:
        - KUBERNETES_MANAGEMENT
        - RESOURCE_MONITORING
        - AUTO_SCALING
        - DEPLOYMENT_AUTOMATION
      specializations:
        - Kubernetes orchestration
        - Helm chart management
        - Resource optimization
        - Security patching
      constraints:
        - Must use resource limits
        - Must implement health checks
        - Never use latest tags in production
      performance:
        tasksCompleted: 0
        successRate: 0.90
        averageTime: 180000
        lastActive: "2025-01-01T00:00:00Z"

    - id: quality-assurance-agent
      name: Quality Assurance Agent
      type: quality-assurance
      autonomyLevel: SUPERVISED
      capabilities:
        - CODE_REVIEW
        - SECURITY_SCANNING
        - PERFORMANCE_TESTING
        - COMPLIANCE_CHECKING
        - TEST_GENERATION
      specializations:
        - Automated testing
        - Security analysis
        - Performance benchmarking
        - Code quality metrics
      constraints:
        - Must achieve 80% coverage
        - Must scan for vulnerabilities
        - Must validate performance SLAs
      performance:
        tasksCompleted: 0
        successRate: 0.94
        averageTime: 90000
        lastActive: "2025-01-01T00:00:00Z"

  communication:
    channels:
      - id: agent-coordination
        type: agent-to-agent
        priority: medium
        encryption: true
        authentication: jwt
        retryPolicy:
          maxAttempts: 3
          backoffMultiplier: 2
          initialDelay: 1000

      - id: human-escalation
        type: escalation
        priority: high
        encryption: true
        authentication: jwt
        retryPolicy:
          maxAttempts: 5
          backoffMultiplier: 1.5
          initialDelay: 500
        integrations:
          slack:
            channel: "#gis-platform-alerts"
            webhook: "${SLACK_WEBHOOK_URL}"
          email:
            recipients:
              - "devops@gis-platform.com"
              - "oncall@gis-platform.com"
          pagerduty:
            serviceKey: "${PAGERDUTY_SERVICE_KEY}"

      - id: system-broadcast
        type: broadcast
        priority: low
        encryption: false
        authentication: api-key

  monitoring:
    metrics:
      collection:
        interval: 30     # seconds
        retention: 2592000 # 30 days
      storage:
        type: prometheus
        endpoint: "http://prometheus:9090"
      alerting:
        rules:
          - name: "high_error_rate"
            condition: "error_rate > 0.1"
            severity: critical
          - name: "slow_response"
            condition: "p95_response_time > 5000"
            severity: warning
          - name: "low_success_rate"
            condition: "success_rate < 0.8"
            severity: error

    dashboards:
      - name: "System Overview"
        panels:
          - task_completion_rate
          - agent_health_status
          - autonomy_decisions
          - quality_gate_results
      - name: "Agent Performance"
        panels:
          - tasks_per_agent
          - success_rate_by_agent
          - response_time_distribution
          - resource_utilization

  security:
    authentication:
      type: jwt
      secretKey: "${JWT_SECRET_KEY}"
      expirationTime: 3600 # 1 hour
    authorization:
      rbac:
        enabled: true
        roles:
          - name: admin
            permissions:
              - "*"
          - name: operator
            permissions:
              - "read:agents"
              - "write:tasks"
              - "read:metrics"
          - name: viewer
            permissions:
              - "read:*"
    encryption:
      inTransit: true
      atRest: true
      algorithm: "AES-256-GCM"

  compliance:
    auditLogging:
      enabled: true
      level: detailed
      storage: "s3://gis-platform-audit-logs"
      retention: 2555 # 7 years
    dataPrivacy:
      gdprCompliant: true
      dataMinimization: true
      consentManagement: true
    changeControl:
      requireApproval: true
      approvers:
        - "senior-engineer"
        - "tech-lead"
      documentationRequired: true

  backup:
    schedule: "0 2 * * *" # Daily at 2 AM
    retention:
      daily: 7
      weekly: 4
      monthly: 12
    storage: "s3://gis-platform-backups"
    encryption: true
    verification: true

  disaster_recovery:
    rto: 3600      # 1 hour
    rpo: 900       # 15 minutes
    replication:
      enabled: true
      regions:
        - us-west-2
        - us-east-1
    failover:
      automatic: false
      testSchedule: "0 3 * * 6" # Weekly on Saturday