apiVersion: apps/v1
kind: Deployment
metadata:
  name: claude-qra-001
  namespace: claude-agents
  labels:
    agent.claude.anthropic.com/id: QRA-001
    agent.claude.anthropic.com/type: quality-review
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      agent.claude.anthropic.com/id: QRA-001
  template:
    metadata:
      labels:
        agent.claude.anthropic.com/id: QRA-001
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: claude-qra
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: agent
        image: ghcr.io/anthropics/claude-agent:qra-v2.0.0
        imagePullPolicy: Always
        ports:
        - name: metrics
          containerPort: 9090
          protocol: TCP
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
            ephemeral-storage: "10Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
            ephemeral-storage: "20Gi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: CLAUDE_API_KEY
          valueFrom:
            secretKeyRef:
              name: claude-credentials
              key: api-key
        - name: AGENT_ID
          value: "QRA-001"
        - name: LOG_LEVEL
          value: "INFO"
        volumeMounts:
        - name: workspace
          mountPath: /workspace
          readOnly: true
        - name: cache
          mountPath: /cache
      volumes:
      - name: workspace
        hostPath:
          path: ${PWD}
          type: Directory
      - name: cache
        emptyDir:
          sizeLimit: 10Gi
